project: 
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
          - text: "R Data Analysis Exercise"
            href: ./dataanalysis_exercise.html
      - text: "Flu Analysis"
        menu: 
          - text: "Wrangling Code"
            href: ./Fluanalysis_exercise/code/wrangling.html 
          - text: "Exploration"
            href: ./Fluanalysis_exercise/code/exploration.html 
          - text: "Fitting"
            href: ./Fluanalysis_exercise/code/Fitting.html
          - text: "Evaluation"
            href: ./Fluanalysis_exercise/code/modeleval.html            
    right:
      - icon: github 
        href: https://github.com/Jacobmatta/jacobmatta-MADA-portfolio/        

format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE


